# Generated by Django 4.1.7 on 2023-05-12 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skarbonka', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skarbonka',
            name='child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='child', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
